### ISSUE TITLE
Error in Inflector

### ISSUE THREAD

**Issue by RobertoBarros** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#1]
I was having this error when ST load the plugin:

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./rails_switcher.py", line 2, in <module>
    from lib.inflector import *
  File "./lib/inflector/__init__.py", line 7, in <module>
    from languages.spanish import Spanish
ImportError: No module named spanish
```

So I removed the line 7 in **lib/inflector/**init**.py**:

``` python
     from languages.spanish import Spanish
```

**Comment by AlexanderZaytsev** [comment]
Thanks for letting me know, this is fixed in https://github.com/AlexanderZaytsev/SublimeText2RailsFileSwitcher/commit/90c0e9ee33e27a3609fad683f2b38eecbab07207
